### ISSUE TITLE
Not working on Opera

### ISSUE THREAD

**Issue by AkaPvto** [Araxeus/Youtube-Volume-Scroll#105]
I know there isn't an specific version for Opera but the Chrome one doesn't work for it.

I recently change from one to the other and I was used to this addon but I seems like it doesn't work on Opera.
Is there any way to make it work? It looks like there is not an equivalent for the browser neither so . . .

**Comment by Araxeus** [comment]
I've actually just downloaded Opera to check and it worked on first try?

**Comment by Araxeus** [comment]
I've also download Opera GX and it works there too
