### ISSUE TITLE
Request: Add option to modify rate of volume change

### ISSUE THREAD

**Issue by rekadoodle** [Araxeus/Youtube-Volume-Scroll#3]
I'd like to be able to radically change the volume with only a scroll or two but I find the default setting requires far more scrolling than I am comfortable with. I couldn't find any way to change this (no config?) so I'm requesting this as a feature. Thanks!

**Comment by Araxeus** [comment]
Where/how would you want to change it?

Any suggestions/ideas?

Maybe a little menu that opens when you click the button of the extension?
(Said button is currently disabled)

**Comment by rekadoodle** [comment]
That suggestion you made sounds ideal, whatever is easiest should be fine also. A slider would be nice if you use a menu.
I guess the value is the % per scroll? If so then 1-20 range sounds great!

Another thing I would find useful is if you could mute/unmute the player with a middle click.

**Comment by Araxeus** [comment]
Ill try to find some free time to implement this feature.

Thank you for the suggestion :)

**Comment by Araxeus** [comment]
@rekadoodle could you check out the #4 and try it out as unpacked extension?

would love some feedback if there is any

**Comment by rekadoodle** [comment]
Tried it for the past day and it's amazing! UI is great and the functionality is perfect for me now

**Comment by Araxeus** [comment]
New version has been publish on the chrome webstore :)
