### ISSUE TITLE
Video speed control prompt is not displayed

### ISSUE THREAD

**Issue by zjwww** [Araxeus/Youtube-Volume-Scroll#32]
With the latest version update, I found the video speed control prompt text is not displayed with native hud. hope you can fix this soon.

**Comment by Araxeus** [comment]
> video speed control prompt tex

You mean the volume overlay isn't showing up?

It's showing with custom mode but not native?

Can you check and see if there are any errors in the extensions page?

![image](https://user-images.githubusercontent.com/78568641/219084915-abcc23ef-2346-4509-8a3c-8732224114a9.png)

**Comment by zjwww** [comment]
Hi Araxeus, I mean when I use this plugin in youtube website, only the video speed control overlay not showing up,
I am using the latest Microsoft Edge with the plugin from google chrome store, after finding this issue I change to reinstall the plugin from Microsoft Store, but still the same, the problem is in all 3 modes (custom/native/none).
There is no errors in my edge extension page currently. thanks.
<img width="1007" alt="Untitled" src="https://user-images.githubusercontent.com/13580677/219090353-96c76a9b-6b14-41a6-8764-e385daa53ace.png">

**Comment by zjwww** [comment]
Hi Araxeus, 
I mean when I use this plugin in youtube website, only the video speed control overlay not showing up,
I am using the latest Microsoft Edge with the plugin from google chrome store, after finding this issue I change to reinstall the plugin from Microsoft Store, but still the same, the problem is in all 3 modes (custom/native/none).
Attatched some error info. thanks.
<img width="914" alt="Untitled" src="https://user-images.githubusercontent.com/13580677/219091337-df6922e3-8e83-4782-9c56-d24664af8a3c.png">
[er.txt](https://github.com/Araxeus/Youtube-Volume-Scroll/files/10745258/er.txt)

**Comment by Araxeus** [comment]
Ok, I have found and fixed the error in the latest commit in #29 

A new version will be released this week with many improvements, including this fix 🥳

**Comment by zjwww** [comment]
Great and thanks, I am looking forward to the update.
