### ISSUE TITLE
Only adjust volume when right click is held

### ISSUE THREAD

**Issue by PhantomGamers** [Araxeus/Youtube-Volume-Scroll#35]
Enhancer for Youtube has this option where volume adjustments can be made to only take effect when the right click button is held down when the scroll wheel is used. Otherwise the scroll wheel will behave normally and allow scrolling the page. I think this would be a good feature for this extension as well.

**Comment by Araxeus** [comment]
Thank you for the suggestion. I'm working on adding `Required Modifier Keys` now

For this initial draft, it's either <kbd>Shift</kbd> or <kbd>Right Click</kbd>

![image](https://user-images.githubusercontent.com/78568641/219437066-01570db0-74e0-4970-8435-a400922058d8.png) ![image](https://user-images.githubusercontent.com/78568641/219437046-e6358aed-d39f-458b-8579-e232a53d2b6b.png)
