### ISSUE TITLE
Can't modify volume when the song/video is in a playlist..

### ISSUE THREAD

**Issue by Catalin2008** [Araxeus/Youtube-Volume-Scroll#9]
When you try to modify the volume with your scrollwheel on a video/song that is in a playlist extension doesn't work.

**Comment by Araxeus** [comment]
Can't replicate this, It works perfectly for me

care to share a screenshot like this? (`ctrl`+`shift`+`i` to bring up devtools, then click console and select index.js in messages)
![image](https://user-images.githubusercontent.com/78568641/158245692-80b648a1-27e7-41bd-aa6b-9bfd74ae9b93.png)

**Comment by Catalin2008** [comment]
Sorry for late response.. I want to mention that it doesn't happen all time but it happens..
https://youtu.be/VEzeJtu7n_0

**Comment by Araxeus** [comment]
Very weird, it says it loaded but doesn't work without any errors...

Not sure why or how this would happen 😞
